# Generated by Django 5.2.7 on 2025-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.TextField(max_length=250, unique=True)),
                ('cantidadHorasCurso', models.IntegerField(unique=True)),
            ],
        ),
    ]
