# Generated by Django 5.2.7 on 2025-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(related_name='estudiantes', to='estudiante.curso'),
        ),
    ]
