# Generated by Django 5.2.7 on 2025-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='notaCursoEstudiante',
            field=models.IntegerField(null=True),
        ),
    ]
